cursor_shape          Underline
cursor_underline_thickness 1
window_padding_width  20

# Special
foreground #d1c3f4
background #211720

# Black
color0 #86606d
color8 #86606d

# Red
color1 #f7262b
color9 #f7262b

# Green
color2  #adf182
color10 #adf182

# Yellow
color3  #f5c024
color11 #f5c024

# Blue
color4  #523874
color12 #523874

# Magenta
color5  #916cad
color13 #916cad

# Cyan
color6  #a8e4f0
color14 #a8e4f0

# White
color7  #e9d5d3
color15 #e9d5d3

# Cursor
cursor #dc7d68
cursor_text_color #dc7d68

# Selection highlight
selection_foreground #9590bd
selection_background #6e3e58
